### ISSUE TITLE
Range iterator for Bptreemap

### ISSUE THREAD

**Issue by carllin** [kanidm/concread#44]
Would be nice for BptreeMap to support a "range" function like: https://www.cs.brandeis.edu/~cs146a/rust/doc-02-21-2015/std/collections/struct.BTreeMap.html#method.range

**Comment by Firstyear** [comment]
Indeed, there are some comments in the code about a future desire to add this feature, but so far it hasn't been required by any projects that I use concread in. So I will probably work on this within the next few months, but if you need it sooner, I'm happy to help advise and support if you want to implement it. 

Thanks!
