### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [kanidm/concread#45]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the README, which says `cargo miri test -- -Zmiri-disable-isolation`. That should become `MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test`.

`cargo miri setup` is also not needed any more.

**Comment by Firstyear** [comment]
Great, I'll update this in the readme. What version does this take effect from? Latest nightly I assume :) 

Thanks for letting me know!

**Comment by Firstyear** [comment]
If you have a bit of time to advise on a problem @RalfJung I'm seeing a new error with Miri here. I'm pretty certain it's a mistake in my code, but I can't quite work out how. 

```
running 77 tests
test bptree::cursor::tests::test_bptree2_cursor_insert_leaf ... error: Undefined Behavior: incorrect layout on deallocation: allocation has size 128 and alignment 128, but gave size 120 and alignment 8
    --> /home/william/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:92:14
     |
92   |     unsafe { __rust_dealloc(ptr, layout.size(), layout.align()) }
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ incorrect layout on deallocation: allocation has size 128 and alignment 128, but gave size 120 and alignment 8
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information

     = note: inside `std::alloc::dealloc` at /home/william/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:92:14
     = note: inside `<std::alloc::Global as std::alloc::AllocRef>::dealloc` at /home/william/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:225:22
     = note: inside `smallvec::alloc::alloc::box_free::<bptree::node::Leaf<usize, usize>>` at /home/william/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:320:9
     = note: inside `std::intrinsics::drop_in_place::<std::boxed::Box<bptree::node::Leaf<usize, usize>>> - shim(Some(std::boxed::Box<bptree::node::Leaf<usize, usize>>))` at /home/william/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
note: inside `bptree::node::Leaf::<usize, usize>::free` at src/bptree/node.rs:784:9
    --> src/bptree/node.rs:784:9
     |
784  |         }
     |         ^
note: inside `bptree::node::Node::<usize, usize>::free` at src/bptree/node.rs:430:26
    --> src/bptree/node.rs:430:26
     |
430  |             FLAG_LEAF => Leaf::free(node as *mut Leaf<K, V>),
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside closure at src/bptree/cursor.rs:495:45
    --> src/bptree/cursor.rs:495:45
     |
495  |         self.first_seen.iter().for_each(|n| Node::free(*n))
     |                                             ^^^^^^^^^^^^^^
```

The code in question is related to https://github.com/kanidm/concread/blob/master/src/bptree/node.rs#L781 . Given my background in C, that's how I approached this library which is why I'm using the raw pointers. Saying this, the test passes under address sanitiser, but I think miri is more sensitive to correctness issues. So I'm wondering you have some advice here about what might be occuring and how I could resolve it. (Honestly, I probably should rewrite in terms of NonNull and transmute rather than *mut and pointer casting). 

Thanks!

**Comment by RalfJung** [comment]
> What version does this take effect from? Latest nightly I assume :)

Yes, starting with yesterday's nightly (2020-09-21).

That BTree bug is an interesting one, and it's not even "just" an aliasing violation... basically what it says is, you need to make sure that when deallocating a block of memory you use the exact same size and alignment as you did when allocating the block. But the block being deallocated there has size 128, while `layout.size()` is 120. Since this is inside a `Box`, this indicates that you allocated the `Box` with one type but deallocated it with another, which is only allowed if both types have the same size (and alignment).

I should probably make it show the allocation ID there so that one can use allocation tracking to also figure out when and where the block was allocated before.

**Comment by Firstyear** [comment]
@RalfJung You know what, your right. I forgot that I wrapped nodes in the CachePadded type from crossbeam. :) Sorry for the noise and appreciate your advice as always. Thanks!
