### ISSUE TITLE
implement DoubleEndedIterator for BptreeMap

### ISSUE THREAD

**Issue by ydprycto** [kanidm/concread#73]
would allow usage of the BptreeMap iter same as the original

**Comment by Firstyear** [comment]
Hey there! Yeah it would be cool to have this. I don't think the iterator code is "too complex" so if you wanted to have a go at it, I'd be happy to review and mentor. Otherwise I'll try to look at this in the coming weeks :) I just have other priorities right now sorry.

**Comment by Firstyear** [comment]
I had a look into this, and it's not a simple task, so it may take me a bit to get to it due to other pressing matters. But I will do it the future as there are a number of improvements to the library I want to make :)
