### ISSUE TITLE
Better wasm support

### ISSUE THREAD

**Issue by mockfox** [kanidm/concread#75]
This crate does not compile to wasm as-is due to a dependency on `ahash` or rather its dependency `getrandom`. It is relatively easy to get it to compile by pinning the `getrandom` dependency with the `js` feature. It would be nice to not need to do this, ie. this crate could support a different hash algorithms like `wyhash` which only depends on `rand-core` and compiles to wasm without issue.

**Comment by Firstyear** [comment]
Hey @mockfox what are you trying to achieve using this crate inside of wasm? Most of the value here is in multi-threaded contexts, so I'm wondering if you just are after the concurrently readable cell types, or if you really want all the hashtrie/hashmap functionality. That'll help me know what the right thing to do is to fix this.

**Comment by mockfox** [comment]
At the moment, I am using HashMap although the other concurrent types would also be useful in other projects. I am using it in a multithreaded context ([wasm_bindgen_futures](https://docs.rs/wasm-bindgen-futures/0.4.30/wasm_bindgen_futures/#).

**Comment by Firstyear** [comment]
So I think the best option in this case is:

* Add a feature for arcache, enabled by default
* Add a feature for ahash, enabled by default
* When ahash isn't enabled, we use the std default hasher

That should let you use this with wasm, provided you set --default-features=false.

How does that sound?

**Comment by mockfox** [comment]
It does make sense to use the std hasher when the ahash feature is disabled, just to get the crate to compile to wasm on its own. I think that suggesting wyhash perhaps should have been a separate issue of its own since I have no need for a DOS-resistant hasher and I believe wyhash is faster.

**Comment by Firstyear** [comment]
Done! Please upgrade to 0.3.4, and you'll find all the features there. Should also be documented on docs.rs.
